version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - mvn clean
    - mvn validate
    - echo Pre-build completed on 'date'
  build:
    commands:
    - echo Build completed 'date'
    - mvn compile
    - mvn test
  post_build:
    commands:
    - echo Build completed 'date'
    - mvn package
    - mv target/*.war java-codebuld.war
artifacts:
  files:
    - java-codebuld.war